# Use the official Airflow image
FROM apache/airflow:2.10.5-python3.11

# Set Airflow environment variables
ENV AIRFLOW_HOME="/app/airflow"
ENV AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=1000
ENV AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False
ENV AIRFLOW__CORE__DAGS_FOLDER="/app/dags"

# Copy DAGs
COPY dags /app/dags

# Set working directory
WORKDIR /app

# Default command
CMD ["airflow", "scheduler"]
