services:
  airflow:
    image: airflow-image
    container_name: airflow-containe
    build:
      context: .
      dockerfile: Dockerfile.ariflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/app/dags
      - ./src:/app/src
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    networks:
      - airflow-network
    entrypoint: ["/bin/sh", "-c", "chmod +x /app/start.sh && /app/start.sh"]

networks:
  airflow-network:
    driver: bridge

