
replicaCount: 0

image:
  repository: sparkpred
  tag: latest
  pullPolicy: Never

sqlserver:
  host:
    secretName: "db-secrets-pred"
    secretKey: "host"  
  port:
    secretName: "db-secrets-pred"
    secretKey: "port"  
  database:
    secretName: "db-secrets-pred"
    secretKey: "database" 
  username:
    secretName: "db-secrets-pred"
    secretKey: "username" 
  password:
    secretName: "db-secrets-pred"
    secretKey: "password" 
  table:
    secretName: "db-secrets-pred"
    secretKey: "table" 

mongodb:
  enabled: true
  auth:
    enabled: false
  architecture: standalone
  replicaCount: 1
  persistence:
    enabled: true
    size: 512Mi  
  resources:
    requests:
      cpu: "100m"    
      memory: "256Mi" 
    limits:
      cpu: "300m"    
      memory: "512Mi" 
  service:
    type: ClusterIP
    port: 27017
  connectionUri:
    secretName: "db-secrets-pred"
    secretKey: "mongodb"

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

serviceAccount:
  create: true  
  name: "spark-prediction"

rbac:
  create: true
  roleName: "spark-pred-cluster-role" 
  roleBindingName: "spark-pred-rolebinding"
  namespace: "argo"  

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80



job:
  restartPolicy: Never
  ttlSecondsAfterFinished: 3600

tolerations: []
nodeSelector: {}
affinity: {}

config:
  enabled: true

workflow:
  enabled: true

server:
  authMode: "server"  
  secure: false 

model_eval:
  theshold_value: 0.02      

volumeClaims:
  data:
    size: 1Gi
    accessMode: ReadWriteOnce
  model:
    size: 1Gi
    accessMode: ReadWriteOnce

dataConsumer:
  persistence:
    enabled: true
    existingClaim: "data-consumer-pvc"  
    mountPath: "/data/inbox-data/"          
    readOnly: true                      

model:
  persistence:
    enabled: true
    existingClaim: "model-pvc"         
    mountPath: "/app/saved_models"         
    readOnly: true                      

predictionStorage:
  existingClaim: "predict-pvc"


