global:
  storageClass: "standard"

replicaCount: 3

auth:
  enabled: false  

kraft:
  enabled: true
  clusterId: "5bd2abf2-10a6-494d-a783-6b9f4a0c72ca"

listeners:
  client:
    protocol: PLAINTEXT
    port: 9092
    advertisedListeners:
      - PLAINTEXT://kafka.default.svc.cluster.local:9092

persistence:
  enabled: true
  size: 8Gi

service:
  type: ClusterIP
  ports:
    client: 9092
    controller: 9093
    interbroker: 9094

replicaCount: 1

kafkaSidecars:
  enabled: true 
  image:
    repository: pythonkafka
    tag: latest
    pullPolicy: Never

  env:
    GCP_PROJECT_ID: "data-prediction-pipe-data"
    TOPIC_NAME: "my-gcs-data"
    TOPIC_NAME_SUB: "my-gcs-data-sub"
    PREDICTION_BUCKET_NAME: "aml-data-bucket"
    KAFKA_BOOTSTRAP_SERVERS: "kafka.default.svc.cluster.local:9092"
    FILE_PATTERN: "Transactions_\\d{8}_\\d{6}\\.csv$"

  gcs:
    existingSecret: "gcp-service-account"
    secretKey: "key.json"

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  persistence:
    enabled: true
    size: 4Gi
    storageClass: "csi-hostpath-sc"
