apiVersion: v1
kind: Service
metadata:
  name: spark-ui
spec:
  selector:
    app: my-prediction-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 31567  