apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{ .Release.Name }}-workflow
  namespace: argo
spec:
  serviceAccountName: {{ .Values.serviceAccount.name }}
  entrypoint: prediction-pipeline
  volumes:
    - name: shared-data
      persistentVolumeClaim:
        claimName: {{ .Values.dataConsumer.persistence.existingClaim }}
    - name: model-volume
      persistentVolumeClaim:
        claimName: {{ .Values.model.persistence.existingClaim }}

  templates:
    - name: prediction-pipeline
      steps:
        - - name: file-watcher
            template: watcher-step
        
    - name: watcher-step
      container:
        name: my-prediction-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Never
        command: ["/opt/venv/bin/python"]  
        args: ["/app/file_watcher.py"]  

        volumeMounts:
          - name: shared-data
            mountPath: {{ .Values.dataConsumer.persistence.mountPath }}
            readOnly: {{ .Values.dataConsumer.persistence.readOnly }}
          - name: model-volume
            mountPath: {{ .Values.model.persistence.mountPath }}
            readOnly: {{ .Values.model.persistence.readOnly }}
          
        env:
          - name: PYSPARK_PYTHON
            value: /opt/venv/bin/python
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: JAVA_HOME
            value: "/opt/java/openjdk"
          - name: HADOOP_HOME
            value: "/opt/hadoop"
          - name: HADOOP_CONF_DIR
            value: "/opt/hadoop/etc/hadoop"
          - name: SPARK_HOME
            value: "/opt/spark"
          - name: SPARK_LOCAL_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
         
          # Spark Core Configuration   
          - name: SPARK_DRIVER_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SPARK_DRIVER_PORT
            value: "29413"
          - name: SPARK_UI_PORT
            value: "4040"
          - name: SPARK_MASTER
            value: "local[2]"
          - name: SPARK_APP_NAME
            value: "my-prediction-app"
          - name: SPARK_K8S_IMAGE
            value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          - name: SPARK_K8S_NAMESPACE
            value: "argo"
          - name: SPARK_K8S_SERVICE_ACCOUNT
            value: "{{ .Values.serviceAccount.name }}"
          - name: SPARK_K8S_BATCH_DELAY
            value: "5s"
          - name: SPARK_EXECUTOR_MEMORY
            value: "768m"
          - name: SPARK_DRIVER_MEMORY
            value: "1g"
          - name: SPARK_MEMORY_FRACTION
            value: "0.6"
          - name: SPARK_STORAGE_FRACTION
            value: "0.5"
          - name: SPARK_SHUFFLE_PARTITIONS
            value: "2"
          - name: SPARK_DEFAULT_PARALLELISM
            value: "2"
          - name: SPARK_SERIALIZER
            value: "org.apache.spark.serializer.KryoSerializer"
          - name: SPARK_KARYO_BUFFER_MAX
            value: "64m"
          - name: SPARK_UI_ENABLED
            value: "true"
          - name: SPARK_UI_REVERSE_PROXY
            value: "true"
          - name: model_saved
            value: {{ .Values.model.persistence.mountPath }}
          - name: DATA_DIR
            value: {{ .Values.dataConsumer.persistence.mountPath }}
        resources:
          requests:
            cpu: "300m"        
            memory: "1.5Gi"
          limits:
            cpu: "400m"
            memory: "3Gi"