apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      serviceAccountName: spark #added for role and service account of spark
      containers:
        - name: my-python-app
          image: mypyspark:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: JAVA_HOME
              value: "/usr/lib/jvm/java-17-openjdk-amd64"
            - name: HADOOP_VERSION
              value: "3.3.6"
            - name: SPARK_VERSION
              value: "3.5.5"
            - name: SPARK_HOME
              value: "/opt/spark"
            - name: MONGO_DB_URL  # MongoDB URL from Kubernetes Secret
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: mongodb
            - name: STARTUP_COMMAND  # Fetch startup command from ConfigMap
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: startup-command
          volumeMounts:
            - name: app-storage
              mountPath: /app/artifact  # Path to store artifacts
            - name: config-volume
              mountPath: /app/config  # Path to store configuration files
          command: ["/bin/sh", "-c"]
          args: ["$(STARTUP_COMMAND)"]  # Run install + start app dynamically from ConfigMap
          resources:
            limits:
              memory: "8Gi"
              cpu: "4"
            requests:
              memory: "2Gi"
              cpu: "2"
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc  # Ensure this PVC exists
        - name: config-volume
          configMap:
            name: app-config  # Ensure this ConfigMap contains spark_config.json