apiVersion: v1
kind: Service
metadata:
  name: argo-server
  namespace: argo
spec:
  type: NodePort
  selector:
    app: argo-server
  ports:
    - port: 2746
      targetPort: 2746
      nodePort: 30080
      protocol: TCP

