apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  requirements.txt: |
    pandas
    numpy
    google-cloud-storage==3.0.0
    pyodbc
    python-dotenv
    pyspark
    tqdm
    pyarrow
    venv-pack 
    pymongo
    flask
    watchdog
    requests
    kafka-python
    confluent-kafka
    PyYAML
  spark_config.json: |
    {
      "master": "k8s://https://192.168.49.2:8443",
      "spark.kubernetes.container.image": "mypyspark:latest",
      "spark.kubernetes.namespace": "default",
      "spark.driver.memory": "3g",
      "spark.executor.memory": "6g",
      "spark.executor.instances": "2",
      "spark.executor.cores": "2",
      "spark.sql.shuffle.partitions": "50",
      "spark.kubernetes.authenticate.driver.serviceAccountName": "spark"
    }
  startup-command: "/opt/venv/bin/python /app/test.py"
