apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: scheduled-ml-training
  namespace: argo
spec:
  schedule: "15 16 * * *"  
  timezone: "America/Toronto"  
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  workflowSpec:
    workflowTemplateRef:
      name: pyspark-ml-training-template