apiVersion: v1
kind: Service
metadata:
  name: my-python-app-headless
spec:
  clusterIP: None
  selector:
    app: my-python-app
  ports:
    - name: spark-ui
      port: 4040
    - name: spark-driver
      port: 7078
    - name: flask-ui
      port: 5000
