{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-argo-clusterrole  # Simplified naming
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete", "deletecollection"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflowtaskresults", "workflowtemplates"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-argo-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: "argo"
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-argo-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end }}