apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: my-python-app
spec:
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

  