apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/app/artifact"  
