{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.roleName }} 
rules:
- apiGroups: [""]                   # Core API group
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/log"]
  verbs: ["create", "get"]
- apiGroups: ["apps"]               # Apps API group
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]              # Batch API group (for Spark jobs)
  resources: ["jobs"]
  verbs: ["*"]
{{- end }}