{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.roleBindingName }} 
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}   
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.roleName }}         
  apiGroup: rbac.authorization.k8s.io
{{- end }}