{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.roleBindingName }}
  namespace: default
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}  # Ensure Spark uses this
  namespace: default
roleRef:
  kind: Role
  name: {{ .Values.rbac.roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
