{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.roleName }}
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "configmaps", "services", "persistentvolumeclaims"]
  verbs: ["create", "get", "list", "watch", "delete", "deletecollection"]
{{- end }}
