apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gcs-microservice.fullname" . }}
  labels:
    {{- include "gcs-microservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gcs-microservice.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "gcs-microservice.labels" . | nindent 8 }}
    spec:
      containers:
        - name: kafka-producer
          image: "{{ .Values.kafkaSidecars.image.repository }}:{{ .Values.kafkaSidecars.image.tag }}"
          imagePullPolicy: {{ .Values.kafkaSidecars.image.pullPolicy }}
          env:
            - name: RUN_MODE
              value: "producer"
            {{- range $key, $value := .Values.kafkaSidecars.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: gcp-key
              mountPath: /etc/gcp-key
              readOnly: true
            {{- if .Values.kafkaSidecars.persistence.enabled }}
            - name: processed-files
              mountPath: /var/processed-files
            {{- end }}
          resources:
            {{- toYaml .Values.kafkaSidecars.resources | nindent 12 }}

        - name: kafka-consumer
          image: "{{ .Values.kafkaSidecars.image.repository }}:{{ .Values.kafkaSidecars.image.tag }}"
          imagePullPolicy: {{ .Values.kafkaSidecars.image.pullPolicy }}
          env:
            - name: RUN_MODE
              value: "consumer"
            {{- range $key, $value := .Values.kafkaSidecars.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: gcp-key
              mountPath: /etc/gcp-key
              readOnly: true
          resources:
            {{- toYaml .Values.kafkaSidecars.resources | nindent 12 }}

      volumes:
        - name: gcp-key
          secret:
            secretName: {{ .Values.kafkaSidecars.gcs.existingSecret }}
            items:
              - key: {{ .Values.kafkaSidecars.gcs.secretKey }}
                path: key.json
        {{- if .Values.kafkaSidecars.persistence.enabled }}
        - name: processed-files
          persistentVolumeClaim:
            claimName: {{ include "gcs-microservice.fullname" . }}-pvc
        {{- end }}
