apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gcs-microservice.fullname" . }}-producer
  namespace: argo
  labels:
    {{- include "gcs-microservice.labels" . | nindent 4 }}
    component: producer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gcs-microservice.fullname" . }}
      component: producer
  template:
    metadata:
      labels:
        {{- include "gcs-microservice.labels" . | nindent 8 }}
        component: producer
    spec:
      containers:
        - name: kafka-producer
          image: "{{ .Values.kafkaSidecars.image.repository }}:{{ .Values.kafkaSidecars.image.tag }}"
          imagePullPolicy: {{ .Values.kafkaSidecars.image.pullPolicy }}
          env:
            - name: RUN_MODE
              value: "producer"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
            {{- range $key, $value := .Values.kafkaSidecars.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: gcp-key
              mountPath: /var/secrets/google
              readOnly: true
          initContainers:
            - name: fix-permissions
              image: busybox
              command: ["sh", "-c", "chmod 644 /var/secrets/google/key.json"]
              volumeMounts:
              - name: gcp-key
                mountPath: /etc/gcp-key
            {{- if .Values.kafkaSidecars.persistence.enabled }}
            - name: processed-files
              mountPath: /var/processed-files
            {{- end }}
          resources:
            {{- toYaml .Values.kafkaSidecars.resources | nindent 12 }}

      volumes:
        - name: gcp-key
          secret:
            secretName: {{ .Values.kafkaSidecars.gcs.existingSecret }}
            items:
              - key: {{ .Values.kafkaSidecars.gcs.secretKey }}
                path: key.json
        {{- if .Values.kafkaSidecars.persistence.enabled }}
        - name: processed-files
          persistentVolumeClaim:
            claimName: {{ include "gcs-microservice.fullname" . }}-producer-pvc
        {{- end }}
