apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-producer-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 4Gi
  storageClassName: csi-hostpath-sc
