apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gcs-microservice.fullname" . }}-consumer-pvc
  labels:
    {{- include "gcs-microservice.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafkaSidecars.persistence.size }}
  {{- if .Values.kafkaSidecars.persistence.storageClass }}
  storageClassName: {{ .Values.kafkaSidecars.persistence.storageClass }}
  {{- end }}