apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-consumer-pvc
  namespace: argo
  labels:
    {{- include "gcs-microservice.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.kafkaSidecars.persistence.size }}
  storageClassName: csi-hostpath-sc
