
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-microservice-gcs-to-kafka-producer-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 