apiVersion: v2
name: mypyspark-app
description: A Helm chart for deploying PySpark with MongoDB on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: mongodb
    version: 16.4.7
    repository: https://charts.bitnami.com/bitnami
