apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  labels:
    app: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect:7.7.0
          ports:
            - containerPort: 8083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "kafka.default.svc.cluster.local:9092"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: "kafka-connect"
            - name: CONNECT_GROUP_ID
              value: "connect-cluster"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "connect-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "connect-statuses"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.storage.StringConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/confluent-hub-components"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/gcp/key.json"
          volumeMounts:
            - name: plugins
              mountPath: /usr/share/confluent-hub-components
            - name: gcp-key
              mountPath: /etc/gcp
      initContainers:
        - name: install-gcs-plugin
          image: confluentinc/cp-kafka-connect:7.7.0
          command:
            - bash
            - -c
            - |
              confluent-hub install --no-prompt confluentinc/kafka-connect-gcs:10.3.1
          volumeMounts:
            - name: plugins
              mountPath: /usr/share/confluent-hub-components
      volumes:
        - name: plugins
          emptyDir: {}
        - name: gcp-key
          secret:
            secretName: gcp-service-account