replicaCount: 1

image:
  repository: confluentinc/cp-kafka-connect
  tag: 7.9.0

kafka:
  bootstrapServers: "PLAINTEXT://kafka.default.svc.cluster.local:9092"

configurationOverrides:
  "key.converter": "org.apache.kafka.connect.storage.StringConverter"
  "value.converter": "org.apache.kafka.connect.json.JsonConverter"
  "offset.storage.topic": "connect-offsets"
  "config.storage.topic": "connect-configs"
  "status.storage.topic": "connect-statuses"
  "offset.storage.replication.factor": "1"
  "config.storage.replication.factor": "1"
  "status.storage.replication.factor": "1"
  "plugin.path": "/usr/share/confluent-hub-components"

env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/gcp/key.json

externalSecrets:
  - name: gcp-service-account
    mountPath: /etc/gcp

initContainers:
  - name: install-plugins
    image: confluentinc/cp-kafka-connect:7.9.0
    command:
      - sh
      - -c
      - |
        confluent-hub install --no-prompt confluentinc/kafka-connect-gcs:latest
    volumeMounts:
      - name: plugin-volume
        mountPath: /usr/share/confluent-hub-components

extraVolumeMounts:
  - name: plugin-volume
    mountPath: /usr/share/confluent-hub-components

extraVolumes:
  - name: plugin-volume
    emptyDir: {}
