---
replicaCount: 1

image:
  repository: mypyspark
  tag: latest
  pullPolicy: IfNotPresent

sqlserver:
  host: "192.168.0.23"
  port: "1433"
  database:
    secretName: "db-secrets-new"
    secretKey: "sql_database"
  username:
    secretName: "db-secrets-new"
    secretKey: "sql_username"
  password:
    secretName: "db-secrets-new"
    secretKey: "sql_password"

mongodb:
  secretName: "db-secrets-new"
  secretKey: "mongo_db_url"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

serviceAccount:
  create: true
  name: "my-app-service-account"

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

resources:
  limits:
    memory: "16Gi"  
  requests:
    memory: "2Gi"  

pipelines:
  - name: ingestion
    script: "ingestion_pipeline.py"
    dependencies: []
  - name: validation
    script: "validation_pipeline.py"
    dependencies: ["ingestion"]
  - name: transformation
    script: "transformation_pipeline.py"
    dependencies: ["validation"]
  - name: training
    script: "training_pipeline.py"
    dependencies: ["transformation"]
  - name: evaluation
    script: "evaluation_pipeline.py"
    dependencies: ["training"]
  - name: pusher
    script: "pusher_pipeline.py"
    dependencies: ["evaluation"]
  - name: file_watcher
    script: "file_watcher.py"
    dependencies: []


tolerations: []
nodeSelector: {}
affinity: {}
