---
replicaCount: 1

image:
  repository: mypyspark
  tag: latest
  pullPolicy: IfNotPresent

sqlserver:
  host: "192.168.0.23"
  port: "1433"
  database:
    secretName: "db-secrets-new"
    secretKey: "sql_database"
  username:
    secretName: "db-secrets-new"
    secretKey: "sql_username"
  password:
    secretName: "db-secrets-new"
    secretKey: "sql_password"

mongodb:
  secretName: "db-secrets-new"
  secretKey: "mongo_db_url"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

serviceAccount:
  create: true
  name: "my-app-service-account"

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

resources:
  limits:
    memory: "16Gi"  
  requests:
    memory: "2Gi"  

tolerations: []
nodeSelector: {}
affinity: {}
