apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  requirements.txt: |
    pandas
    numpy
    google-cloud-storage==3.0.0
    pyodbc
    python-dotenv
    pyspark
    tqdm
    pyarrow
    venv-pack 
    pymongo
    flask
    watchdog
    requests
