---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: spark-driver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"

          command: ["spark-submit"]
          args:
            - "--master"
            - "{{ .Values.spark.master }}"
            - "--deploy-mode"
            - "cluster"
            - "--conf"
            - "spark.driver.memory={{ .Values.spark.driverMemory }}"
            - "--conf"
            - "spark.executor.memory={{ .Values.spark.executorMemory }}"
            - "--conf"
            - "spark.executor.cores={{ .Values.spark.executorCores }}"
            - "/app/main.py"

          env:
            - name: SPARK_MASTER
              value: "{{ .Values.spark.master }}"
            - name: SPARK_DRIVER_MEMORY
              value: "{{ .Values.spark.driverMemory }}"
            - name: SPARK_EXECUTOR_MEMORY
              value: "{{ .Values.spark.executorMemory }}"
            - name: SPARK_EXECUTOR_CORES
              value: "{{ .Values.spark.executorCores }}"
            - name: SPARK_TOTAL_EXECUTORS
              value: "{{ .Values.spark.totalExecutors }}"

            - name: SQL_SERVER
              value: "{{ .Values.sqlserver.host }},{{ .Values.sqlserver.port }}"
            - name: SQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.sqlserver.database.secretName }}"
                  key: "{{ .Values.sqlserver.database.secretKey }}"
            - name: SQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.sqlserver.username.secretName }}"
                  key: "{{ .Values.sqlserver.username.secretKey }}"
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.sqlserver.password.secretName }}"
                  key: "{{ .Values.sqlserver.password.secretKey }}"
            - name: MONGO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.mongodb.secretName }}"
                  key: "{{ .Values.mongodb.secretKey }}"
